"""
t-SNE visualization of TCC embeddings colored by phase labels.

Reads ``datasets/embeddings/{run_name}/embd_tsne_phase_label.h5`` (generated by
evaluate.py with ``gen_tsne_phase_label: true``).

Three groups are distinguished by the per-video attributes ``data_type`` and
``is_ground_truth`` stored in that H5 file:

  ┌─────────────────────────────────────┬──────────────┐
  │ Group                               │ Color scheme │
  ├─────────────────────────────────────┼──────────────┤
  │ Training — ground-truth phase label │ Purple       │
  │ Training — SVM-predicted label      │ Blue         │
  │ Validation (any label origin)       │ Red          │
  └─────────────────────────────────────┴──────────────┘

Within each group the 5 phase labels (0–4) are mapped to 5 gradient bins
from light (phase 0) to dark (phase 4).

Usage:
    cd /home/user/zhangzk/projects/fineprog
    python scripts/visualize_embeddings_tsne_phase.py \\
    [--viz_config configs_v2/visualize/tsne_phase.yaml] \
    [--embedding_ref can_ph_valid_ep50k]
"""

import argparse
import os
from datetime import datetime

import h5py
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.lines import Line2D
from matplotlib.patches import Patch
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE
from sklearn.preprocessing import StandardScaler

# ── project root ──────────────────────────────────────────────────────────────

_PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

def _resolve_run_name_v2(embedding_ref: str | None = None) -> str | None:
    """[v2] Get run_name from configs_v2/runs.yaml via ConfigV2."""
    if not embedding_ref:
        return None
    try:
        from utils.config_v2 import ConfigV2
        return ConfigV2().resolve_embedding(embedding_ref).get("run_name")
    except Exception:
        return None


def _resolve_h5_v2(embedding_ref: str) -> str:
    """[v2] Resolve embedding H5 absolute path from runs.yaml registry."""
    from utils.config_v2 import ConfigV2
    return ConfigV2().resolve_embedding(embedding_ref)["embedding_h5_path"]


def resolve_h5_path(cfg: dict, run_name_override: str | None = None, embedding_ref: str | None = None) -> str:
    """Return path to ``embd_tsne_phase_label.h5``.

    Priority:
    1. ``cfg["embedding_h5_path"]`` (explicit override)
    2. [v2] *embedding_ref* → resolved via ConfigV2
    3. ``datasets/embeddings/{run_name}/embd_tsne_phase_label.h5``
         where *run_name* comes from a direct override or the V2 registry.
    """
    if cfg.get("embedding_h5_path"):
        return cfg["embedding_h5_path"]

    # [v2] prefer embedding_ref
    if embedding_ref:
        h5_path = _resolve_h5_v2(embedding_ref)
        print(f"[resolve] [v2] embedding_h5_path → {h5_path}")
        return h5_path

    run_name = run_name_override
    if not run_name:
        raise ValueError(
            "Cannot derive embedding_h5_path: no run_name found.\n"
            "Either provide a run_name override, pass --embedding_ref, or set embedding_h5_path directly in the config file."
        )

    h5_path = os.path.join(
        _PROJECT_ROOT, "datasets", "embeddings", run_name, "embd_tsne_phase_label.h5"
    )
    print(f"[resolve] embedding_h5_path → {h5_path}")
    return h5_path


def resolve_output_dir(cfg: dict, run_name_override: str | None = None, embedding_ref: str | None = None) -> str:
    if cfg.get("output_dir"):
        return cfg["output_dir"]

    run_name = run_name_override or _resolve_run_name_v2(embedding_ref)
    if not run_name:
        run_name = "unknown_run"

    out_dir = os.path.join(_PROJECT_ROOT, "outputs", "tsne", run_name, "tsne_phase")
    print(f"[resolve] output_dir        → {out_dir}")
    return out_dir


def resolve_val_labeled_h5_path(cfg: dict, run_name_override: str | None = None, embedding_ref: str | None = None) -> str | None:
    """Return path to the val labeled H5 (e.g. pouring_val14-14vid-embd-labeled.h5).

    Priority:
    1. ``cfg["val_labeled_h5_path"]`` (explicit override)
    2. ``datasets/embeddings/{run_name}/{val_labeled_dataset_stem}-embd-labeled.h5``

    Returns None if not configured or run_name unavailable.
    """
    if cfg.get("val_labeled_h5_path"):
        return cfg["val_labeled_h5_path"]

    stem = cfg.get("val_labeled_dataset_stem")
    if not stem:
        return None

    run_name = run_name_override or _resolve_run_name_v2(embedding_ref)
    if not run_name:
        return None

    path = os.path.join(
        _PROJECT_ROOT, "datasets", "embeddings", run_name, f"{stem}-embd-labeled.h5"
    )
    print(f"[resolve] val_labeled_h5_path → {path}")
    return path


# ── data loading ──────────────────────────────────────────────────────────────


_GROUP_TRAIN_GT   = "train_gt"
_GROUP_TRAIN_NOGT = "train_nogt"
_GROUP_VAL        = "val"


def _classify_group(data_type: str, is_ground_truth: bool) -> str:
    if data_type == "val":
        return _GROUP_VAL
    if is_ground_truth:
        return _GROUP_TRAIN_GT
    return _GROUP_TRAIN_NOGT


def load_embeddings_from_h5(h5_path: str, cfg: dict):
    """Load all embeddings and phase labels from ``embd_tsne_phase_label.h5``.

    Returns
    -------
    embeddings   : ndarray [N, D]
    phase_labels : ndarray [N]   int64  (0 … n_phases-1)
    groups       : ndarray [N]   str    (_GROUP_TRAIN_GT / _TRAIN_NOGT / _VAL)
    video_names  : ndarray [N]   str
    """
    video_root    = cfg.get("h5_video_root",   "videos")
    embd_key      = cfg.get("embedding_key",   "embeddings")
    phase_key     = cfg.get("phase_labels_key", "phase_labels")

    all_emb, all_phase, all_group, all_vid, all_ford = [], [], [], [], []

    with h5py.File(h5_path, "r") as f:
        videos_grp = f[video_root]
        for vid_id in videos_grp.keys():
            grp = videos_grp[vid_id]
            emb    = grp[embd_key][:]    # [T, D]
            phases = grp[phase_key][:]   # [T]

            data_type       = str(grp.attrs.get("data_type", "train"))
            is_gt_raw       = grp.attrs.get("is_ground_truth", False)
            is_ground_truth = bool(is_gt_raw)

            group = _classify_group(data_type, is_ground_truth)
            T = len(emb)

            all_emb.append(emb)
            all_phase.append(phases)
            all_group.extend([group] * T)
            all_vid.extend([vid_id]  * T)
            all_ford.extend(range(T))

    embeddings   = np.concatenate(all_emb,   axis=0)
    phase_labels = np.concatenate(all_phase, axis=0)
    groups       = np.array(all_group)
    video_names  = np.array(all_vid)
    frame_orders = np.array(all_ford, dtype=np.int64)

    return embeddings, phase_labels, groups, video_names, frame_orders


def load_val_svm_data(h5_path: str, cfg: dict):
    """Load only val-type entries from ``embd_tsne_phase_label.h5``.

    Returns
    -------
    embeddings   : ndarray [N, D]
    svm_labels   : ndarray [N]  int64  SVM-predicted phase labels
    base_vid_ids : ndarray [N]  str    video IDs with any "val_" prefix stripped
    frame_orders : ndarray [N]  int64  0-based frame index within each video
    """
    video_root = cfg.get("h5_video_root",    "videos")
    embd_key   = cfg.get("embedding_key",    "embeddings")
    phase_key  = cfg.get("phase_labels_key", "phase_labels")

    all_emb, all_labels, all_base, all_ord = [], [], [], []
    with h5py.File(h5_path, "r") as f:
        for vid_id in f[video_root].keys():
            grp = f[video_root][vid_id]
            if str(grp.attrs.get("data_type", "train")) != "val":
                continue
            emb    = grp[embd_key][:]
            labels = grp[phase_key][:]
            T      = len(emb)
            base   = vid_id[4:] if vid_id.startswith("val_") else vid_id
            all_emb.append(emb)
            all_labels.append(labels)
            all_base.extend([base] * T)
            all_ord.extend(range(T))

    if not all_emb:
        return np.empty((0, 0)), np.empty(0, np.int64), np.array([]), np.empty(0, np.int64)
    return (
        np.concatenate(all_emb,    axis=0),
        np.concatenate(all_labels, axis=0),
        np.array(all_base),
        np.array(all_ord, dtype=np.int64),
    )


def load_val_gt_phases(h5_path: str, cfg: dict) -> dict:
    """Load ground-truth phase_labels from a labeled H5 file.

    Returns
    -------
    gt_phases : dict  {vid_id (str) -> phase_labels ndarray [T] int64}
                Only videos with ``attrs["labeled"] == True`` are included.
    """
    video_root = cfg.get("h5_video_root",    "videos")
    phase_key  = cfg.get("phase_labels_key", "phase_labels")

    gt: dict = {}
    with h5py.File(h5_path, "r") as f:
        for vid_id in f[video_root].keys():
            grp = f[video_root][vid_id]
            if grp.attrs.get("labeled", False) and phase_key in grp:
                gt[vid_id] = grp[phase_key][:]
    return gt


def align_val_gt_labels(
    svm_emb:      np.ndarray,
    svm_labels:   np.ndarray,
    base_vid_ids: np.ndarray,
    frame_orders: np.ndarray,
    gt_phases:    dict,
):
    """Match GT phase labels to the SVM val data by (video_id, frame_order).

    Returns
    -------
    has_gt     : bool  ndarray [N]   True where a GT label was found
    aligned_gt : int64 ndarray [N]   GT phase labels (-1 where unavailable)
    """
    aligned_gt = np.full(len(svm_labels), -1, dtype=np.int64)
    for i, (vid, t) in enumerate(zip(base_vid_ids, frame_orders)):
        if vid in gt_phases and t < len(gt_phases[vid]):
            aligned_gt[i] = gt_phases[vid][t]
    has_gt = aligned_gt >= 0
    return has_gt, aligned_gt


# ── sampling ─────────────────────────────────────────────────────────────────


def sample_embeddings(embeddings, phase_labels, groups, video_names, frame_orders, cfg: dict):
    """Downsample per video and globally, preserving all arrays in sync."""
    rng             = np.random.default_rng(cfg.get("random_seed", 42))
    max_per_video   = cfg.get("max_frames_per_video", 300)
    max_total       = cfg.get("max_total_frames", 10000)

    unique_videos = np.unique(video_names)
    sel = []
    for vid in unique_videos:
        idx = np.where(video_names == vid)[0]
        if len(idx) > max_per_video:
            idx = rng.choice(idx, size=max_per_video, replace=False)
        sel.append(idx)

    sel = np.concatenate(sel)
    if len(sel) > max_total:
        sel = rng.choice(sel, size=max_total, replace=False)

    return (
        embeddings[sel],
        phase_labels[sel],
        groups[sel],
        video_names[sel],
        frame_orders[sel],
    )


# ── preprocessing + t-SNE ─────────────────────────────────────────────────────


def preprocess_embeddings(embeddings: np.ndarray, cfg: dict) -> np.ndarray:
    if cfg.get("standardize", True):
        embeddings = StandardScaler().fit_transform(embeddings)

    if cfg.get("use_pca_before_tsne", True):
        pca_dim      = cfg.get("pca_dim", 50)
        N, D         = embeddings.shape
        n_components = min(pca_dim, D, N - 1)
        pca          = PCA(n_components=n_components)
        embeddings   = pca.fit_transform(embeddings)
        print(
            f"PCA: {D}→{n_components} dims "
            f"(explained variance: {pca.explained_variance_ratio_.sum():.3f})"
        )

    return embeddings


def run_tsne(embeddings: np.ndarray, cfg: dict):
    N = len(embeddings)
    if N < 10:
        raise ValueError(f"Too few samples for t-SNE: {N}. Need at least 10.")

    tcfg             = cfg.get("tsne", {})
    cfg_perplexity   = tcfg.get("perplexity", 30)
    perplexity       = min(cfg_perplexity, max(5, (N - 1) // 3))
    if perplexity != cfg_perplexity:
        print(f"Adjusted perplexity {cfg_perplexity} → {perplexity}  (N={N})")

    kwargs = dict(
        n_components  = tcfg.get("n_components", 2),
        perplexity    = perplexity,
        learning_rate = tcfg.get("learning_rate", "auto"),
        init          = tcfg.get("init", "pca"),
        random_state  = cfg.get("random_seed", 42),
    )
    max_iter = tcfg.get("max_iter", 1000)
    try:
        tsne   = TSNE(**kwargs, max_iter=max_iter)
        coords = tsne.fit_transform(embeddings)
    except TypeError:
        tsne   = TSNE(**kwargs, n_iter=max_iter)
        coords = tsne.fit_transform(embeddings)

    return coords, perplexity


# ── color palette ─────────────────────────────────────────────────────────────


# Default per-phase colormap names (one distinct family per phase)
_DEFAULT_PHASE_CMAPS = ["Blues", "Greens", "Wistia", "Reds", "Purples"]

# Default cmap lookup values per group (light → dark)
_DEFAULT_SHADES = {
    _GROUP_TRAIN_GT:   0.30,
    _GROUP_TRAIN_NOGT: 0.55,
    _GROUP_VAL:        0.82,
}


def build_phase_palette(n_phases: int, pcfg: dict) -> dict:
    """Return a dict mapping (group_key, phase_int) → RGBA tuple.

    Each phase gets its own color family (sequential colormap).  Within a
    phase the three groups are shaded light → dark:
        Train GT  (lightest)  →  Train SVM  →  Val  (darkest)
    """
    cfg_cmaps = pcfg.get("cmap_phases", _DEFAULT_PHASE_CMAPS)
    # Extend / truncate to exactly n_phases entries
    phase_cmaps = [cfg_cmaps[ph % len(cfg_cmaps)] for ph in range(n_phases)]

    shades = {
        _GROUP_TRAIN_GT:   float(pcfg.get("shade_train_gt",   _DEFAULT_SHADES[_GROUP_TRAIN_GT])),
        _GROUP_TRAIN_NOGT: float(pcfg.get("shade_train_nogt", _DEFAULT_SHADES[_GROUP_TRAIN_NOGT])),
        _GROUP_VAL:        float(pcfg.get("shade_val",        _DEFAULT_SHADES[_GROUP_VAL])),
    }

    palette = {}
    for ph, cmap_name in enumerate(phase_cmaps):
        cmap = plt.get_cmap(cmap_name)
        for grp, shade in shades.items():
            palette[(grp, ph)] = cmap(shade)

    return palette


# ── plotting ──────────────────────────────────────────────────────────────────


def plot_tsne_phase(
    coords:       np.ndarray,
    phase_labels: np.ndarray,
    groups:       np.ndarray,
    cfg:          dict,
    output_dir:   str,
    timestamp:    str | None = None,
):
    """Main phase-label t-SNE scatter plot.

    One scatter call per (group, phase) combination so each sub-population
    gets its own solid colour.  A two-section legend explains:
      • which color family = which group
      • which shade = which phase
    """
    pcfg     = cfg.get("plot", {})
    n_phases = int(cfg.get("n_phases", 5))
    palette  = build_phase_palette(n_phases, pcfg)

    figsize = pcfg.get("figsize", [9, 6])
    dpi     = pcfg.get("dpi", 300)
    s       = pcfg.get("point_size", 5)
    alpha   = pcfg.get("alpha", 0.80)

    lbl = {
        _GROUP_TRAIN_GT:   pcfg.get("label_train_gt",   "Train (GT)"),
        _GROUP_TRAIN_NOGT: pcfg.get("label_train_nogt", "Train (SVM)"),
        _GROUP_VAL:        pcfg.get("label_val",        "Val"),
    }
    mkr = {
        _GROUP_TRAIN_GT:   pcfg.get("marker_train_gt",   "o"),
        _GROUP_TRAIN_NOGT: pcfg.get("marker_train_nogt", "s"),
        _GROUP_VAL:        pcfg.get("marker_val",        "^"),
    }

    group_order = [_GROUP_TRAIN_GT, _GROUP_TRAIN_NOGT, _GROUP_VAL]

    fig, ax = plt.subplots(figsize=figsize)

    for grp in group_order:
        mask_grp = groups == grp
        if not mask_grp.any():
            continue
        for ph in range(n_phases):
            mask = mask_grp & (phase_labels == ph)
            if not mask.any():
                continue
            ax.scatter(
                coords[mask, 0], coords[mask, 1],
                c     = [palette[(grp, ph)]],
                s     = s,
                alpha = alpha,
                marker= mkr[grp],
                linewidths=0,
                zorder=2,
            )

    ax.set_xlabel("t-SNE dim 1")
    ax.set_ylabel("t-SNE dim 2")
    ax.set_title("t-SNE: Phase-Label Coloring\n(color family = phase · shade: Train GT light → Val dark)")
    ax.set_aspect("equal")

    # ── legend ────────────────────────────────────────────────────────────────
    # Section 1: phase color families — one row per phase
    cfg_cmaps   = pcfg.get("cmap_phases", _DEFAULT_PHASE_CMAPS)
    phase_cmaps = [cfg_cmaps[ph % len(cfg_cmaps)] for ph in range(n_phases)]
    shade_mid   = float(pcfg.get("shade_train_nogt", _DEFAULT_SHADES[_GROUP_TRAIN_NOGT]))
    phase_handles = [
        Patch(
            facecolor = plt.get_cmap(phase_cmaps[ph])(shade_mid),
            edgecolor = "none",
            label     = f"Phase {ph}",
        )
        for ph in range(n_phases)
    ]

    # Section 2: group shading — one row per group (marker + gradient description)
    shade_gt   = float(pcfg.get("shade_train_gt",   _DEFAULT_SHADES[_GROUP_TRAIN_GT]))
    shade_nogt = float(pcfg.get("shade_train_nogt", _DEFAULT_SHADES[_GROUP_TRAIN_NOGT]))
    shade_val  = float(pcfg.get("shade_val",        _DEFAULT_SHADES[_GROUP_VAL]))
    ref_cmap   = plt.get_cmap(phase_cmaps[n_phases // 2])  # mid-phase cmap as swatch
    group_shade_map = {
        _GROUP_TRAIN_GT:   shade_gt,
        _GROUP_TRAIN_NOGT: shade_nogt,
        _GROUP_VAL:        shade_val,
    }
    group_handles = []
    for grp in group_order:
        if not (groups == grp).any():
            continue
        group_handles.append(
            Line2D(
                [0], [0],
                marker         = mkr[grp],
                color          = "none",
                markerfacecolor= ref_cmap(group_shade_map[grp]),
                markeredgecolor= "none",
                markersize     = 7,
                label          = f"{lbl[grp]}  (lightest→darkest)"
                                  if grp == _GROUP_TRAIN_GT else lbl[grp],
            )
        )

    leg1 = ax.legend(
        handles       = phase_handles,
        title         = "Phase (color family)",
        loc           = "upper left",
        bbox_to_anchor= (1.01, 1.0),
        borderaxespad = 0,
        fontsize      = 8,
        title_fontsize= 8,
    )
    ax.add_artist(leg1)
    ax.legend(
        handles       = group_handles,
        title         = "Group (shade: GT light → Val dark)",
        loc           = "upper left",
        bbox_to_anchor= (1.01, 0.50),
        borderaxespad = 0,
        fontsize      = 8,
        title_fontsize= 8,
    )

    fname    = f"tsne_phase_{timestamp}.png" if timestamp else "tsne_phase.png"
    out_path = os.path.join(output_dir, fname)
    fig.savefig(out_path, dpi=dpi, bbox_inches="tight")
    plt.close(fig)
    return out_path


def plot_tsne_phase_separate(
    coords:        np.ndarray,
    phase_labels:  np.ndarray,
    groups:        np.ndarray,
    cfg:           dict,
    output_dir:    str,
    timestamp:     str | None = None,
    val_gt_labels: np.ndarray | None = None,
):
    """Panel plot: one subplot per group (3 or 4 panels).

    If *val_gt_labels* is provided (same length as *groups*, -1 = no GT),
    a 4th panel is appended showing the val group coloured by GT phase labels,
    sharing the same t-SNE coordinates as the 3rd (Val SVM) panel.
    """
    pcfg     = cfg.get("plot", {})
    n_phases = int(cfg.get("n_phases", 5))
    palette  = build_phase_palette(n_phases, pcfg)

    dpi   = pcfg.get("dpi", 300)
    s     = pcfg.get("point_size", 5)
    alpha = pcfg.get("alpha", 0.80)
    lbl   = {
        _GROUP_TRAIN_GT:   pcfg.get("label_train_gt",   "Train (GT)"),
        _GROUP_TRAIN_NOGT: pcfg.get("label_train_nogt", "Train (SVM)"),
        _GROUP_VAL:        pcfg.get("label_val",        "Val"),
    }
    mkr = {
        _GROUP_TRAIN_GT:   pcfg.get("marker_train_gt",   "o"),
        _GROUP_TRAIN_NOGT: pcfg.get("marker_train_nogt", "s"),
        _GROUP_VAL:        pcfg.get("marker_val",        "^"),
    }

    group_order   = [_GROUP_TRAIN_GT, _GROUP_TRAIN_NOGT, _GROUP_VAL]
    active_groups = [g for g in group_order if (groups == g).any()]

    # Check whether to add a 4th "Val (GT)" panel
    has_val_gt = (
        val_gt_labels is not None
        and _GROUP_VAL in active_groups
        and (val_gt_labels[groups == _GROUP_VAL] >= 0).any()
    )
    n_col = len(active_groups) + (1 if has_val_gt else 0)
    if n_col == 0:
        print("[plot_tsne_phase_separate] No data found, skipping panel plot.")
        return None

    fig, axes = plt.subplots(1, n_col, figsize=(5 * n_col + 1, 5))
    if n_col == 1:
        axes = [axes]

    # Shared axis limits from all coords
    xpad = (coords[:, 0].max() - coords[:, 0].min()) * 0.04
    ypad = (coords[:, 1].max() - coords[:, 1].min()) * 0.04
    xlim = (coords[:, 0].min() - xpad, coords[:, 0].max() + xpad)
    ylim = (coords[:, 1].min() - ypad, coords[:, 1].max() + ypad)

    cfg_cmaps_p = pcfg.get("cmap_phases", _DEFAULT_PHASE_CMAPS)
    p_cmaps     = [cfg_cmaps_p[ph % len(cfg_cmaps_p)] for ph in range(n_phases)]

    # ── panels 0…n_active-1: one per group ───────────────────────────────────
    for ax, grp in zip(axes[:len(active_groups)], active_groups):
        mask_grp = groups == grp
        for ph in range(n_phases):
            mask = mask_grp & (phase_labels == ph)
            if not mask.any():
                continue
            ax.scatter(
                coords[mask, 0], coords[mask, 1],
                c=[palette[(grp, ph)]], s=s, alpha=alpha,
                marker=mkr[grp], linewidths=0, zorder=2,
            )

        ax.set_xlim(xlim); ax.set_ylim(ylim)
        ax.set_xlabel("t-SNE dim 1"); ax.set_ylabel("t-SNE dim 2")
        ax.set_title(lbl.get(grp, grp))
        ax.set_aspect("equal")

        grp_shade = {
            _GROUP_TRAIN_GT:   float(pcfg.get("shade_train_gt",   _DEFAULT_SHADES[_GROUP_TRAIN_GT])),
            _GROUP_TRAIN_NOGT: float(pcfg.get("shade_train_nogt", _DEFAULT_SHADES[_GROUP_TRAIN_NOGT])),
            _GROUP_VAL:        float(pcfg.get("shade_val",        _DEFAULT_SHADES[_GROUP_VAL])),
        }[grp]
        panel_handles = [
            Patch(facecolor=plt.get_cmap(p_cmaps[ph])(grp_shade),
                  edgecolor="none", label=f"Phase {ph}")
            for ph in range(n_phases)
        ]
        ax.legend(handles=panel_handles, title="Phase",
                  fontsize=7, title_fontsize=7, loc="best")

    # ── panel n_active: Val GT (same t-SNE coords as Val SVM panel) ──────────
    if has_val_gt:
        ax4       = axes[len(active_groups)]
        shade_val = float(pcfg.get("shade_val", _DEFAULT_SHADES[_GROUP_VAL]))
        val_mask  = groups == _GROUP_VAL
        val_coords = coords[val_mask]
        gt_ph_here = val_gt_labels[val_mask]

        # Gray out frames that have no GT label
        no_gt = gt_ph_here == -1
        if no_gt.any():
            ax4.scatter(val_coords[no_gt, 0], val_coords[no_gt, 1],
                        c=["#c8c8c8"], s=s, alpha=0.25, linewidths=0, zorder=1)

        for ph in range(n_phases):
            mask_ph = gt_ph_here == ph
            if not mask_ph.any():
                continue
            ax4.scatter(
                val_coords[mask_ph, 0], val_coords[mask_ph, 1],
                c=[plt.get_cmap(p_cmaps[ph])(shade_val)],
                s=s, alpha=alpha, marker=mkr[_GROUP_VAL], linewidths=0, zorder=2,
            )

        ax4.set_xlim(xlim); ax4.set_ylim(ylim)
        ax4.set_xlabel("t-SNE dim 1"); ax4.set_ylabel("t-SNE dim 2")
        ax4.set_title(f"{lbl.get(_GROUP_VAL, 'Val')} (GT)")
        ax4.set_aspect("equal")

        gt_handles = [
            Patch(facecolor=plt.get_cmap(p_cmaps[ph])(shade_val),
                  edgecolor="none", label=f"Phase {ph}")
            for ph in range(n_phases)
        ]
        ax4.legend(handles=gt_handles, title="Phase (GT)",
                   fontsize=7, title_fontsize=7, loc="best")

    fig.suptitle(
        "t-SNE Phase-Label Coloring — per-group panels\n"
        "(color family = phase · shade: Train GT light → Val dark)",
        fontsize=10,
    )
    fig.tight_layout()

    fname    = f"tsne_phase_panels_{timestamp}.png" if timestamp else "tsne_phase_panels.png"
    out_path = os.path.join(output_dir, fname)
    fig.savefig(out_path, dpi=dpi, bbox_inches="tight")
    plt.close(fig)
    return out_path


def plot_val_svm_vs_gt(
    coords:     "np.ndarray",   # [N, 2]  val-only t-SNE coords
    svm_labels: "np.ndarray",   # [N]  SVM-predicted phase labels
    gt_labels:  "np.ndarray",   # [N]  ground-truth phase labels
    cfg:        dict,
    output_dir: str,
    timestamp:  "str | None" = None,
) -> str:
    """Side-by-side: val embeddings colored by SVM labels (left) vs GT labels (right).

    Both panels share the same t-SNE layout and the same phase -> color mapping.
    Any colour mismatch between panels indicates a SVM classification error.
    """
    pcfg        = cfg.get("plot", {})
    n_phases    = int(cfg.get("n_phases", 5))
    cfg_cmaps   = pcfg.get("cmap_phases", _DEFAULT_PHASE_CMAPS)
    phase_cmaps = [cfg_cmaps[ph % len(cfg_cmaps)] for ph in range(n_phases)]
    shade       = float(pcfg.get("shade_val", _DEFAULT_SHADES[_GROUP_VAL]))
    phase_colors = {ph: plt.get_cmap(phase_cmaps[ph])(shade) for ph in range(n_phases)}

    dpi   = pcfg.get("dpi",        300)
    s     = pcfg.get("point_size", 5)
    alpha = pcfg.get("alpha",      0.80)

    xpad = (coords[:, 0].max() - coords[:, 0].min()) * 0.04
    ypad = (coords[:, 1].max() - coords[:, 1].min()) * 0.04
    xlim = (coords[:, 0].min() - xpad, coords[:, 0].max() + xpad)
    ylim = (coords[:, 1].min() - ypad, coords[:, 1].max() + ypad)

    fig, (ax_svm, ax_gt) = plt.subplots(1, 2, figsize=(12, 5))

    for ax, labels, title in (
        (ax_svm, svm_labels, "Val — SVM predicted"),
        (ax_gt,  gt_labels,  "Val — Ground Truth"),
    ):
        for ph in range(n_phases):
            mask = labels == ph
            if not mask.any():
                continue
            ax.scatter(
                coords[mask, 0], coords[mask, 1],
                c=[phase_colors[ph]], s=s, alpha=alpha, linewidths=0, zorder=2,
            )
        ax.set_xlim(xlim)
        ax.set_ylim(ylim)
        ax.set_xlabel("t-SNE dim 1")
        ax.set_ylabel("t-SNE dim 2")
        ax.set_title(title)
        ax.set_aspect("equal")

    phase_handles = [
        Patch(facecolor=phase_colors[ph], edgecolor="none", label=f"Phase {ph}")
        for ph in range(n_phases)
    ]
    fig.legend(
        handles        = phase_handles,
        title          = "Phase",
        loc            = "center right",
        bbox_to_anchor = (1.10, 0.50),
        fontsize       = 8,
        title_fontsize = 8,
    )
    fig.suptitle(
        "Val: SVM-predicted vs Ground-Truth Phase Labels\n"
        "(same position = same embedding · colour mismatch = classification error)",
        fontsize=10,
    )
    fig.tight_layout()

    fname    = f"tsne_val_svm_vs_gt_{timestamp}.png" if timestamp else "tsne_val_svm_vs_gt.png"
    out_path = os.path.join(output_dir, fname)
    fig.savefig(out_path, dpi=dpi, bbox_inches="tight")
    plt.close(fig)
    return out_path


# ── main ──────────────────────────────────────────────────────────────────────


def main():
    parser = argparse.ArgumentParser(
        description="t-SNE of TCC embeddings colored by phase label."
    )
    parser.add_argument(
        "--viz_config",
        default=None,
        help="[v2] Path to a per-flow visualize YAML override "
             "(default: configs_v2/visualize/tsne_phase.yaml).",
    )
    parser.add_argument(
        "--embedding_ref",
        default=None,
        help="[v2] Embedding alias for primary H5 (overrides the YAML value).",
    )
    parser.add_argument(
        "--no_panels",
        action="store_true",
        help="Skip the three-panel subplot figure.",
    )
    args = parser.parse_args()

    # [v2] Load and resolve via ConfigV2
    from utils.config_v2 import ConfigV2
    _overrides = {}
    if args.embedding_ref:
        _overrides["embedding_ref"] = args.embedding_ref
    cfg = ConfigV2().load_visualize(
        "tsne_phase",
        config_path=args.viz_config,
        overrides=_overrides or None,
    )

    # ── resolved paths ─────────────────────────────────────────────────────────
    h5_path    = cfg["embedding_h5_path"]
    output_dir = cfg["output_dir"]
    os.makedirs(output_dir, exist_ok=True)
    print(f"output_dir: {output_dir}")

    # ── load ───────────────────────────────────────────────────────────────────
    embeddings, phase_labels, groups, video_names, frame_orders = load_embeddings_from_h5(h5_path, cfg)

    n_phases = int(cfg.get("n_phases", 5))
    unique_phases = np.unique(phase_labels)
    print(f"Loaded {len(embeddings)} frames from {len(np.unique(video_names))} videos")
    print(f"  train-GT   : {(groups == _GROUP_TRAIN_GT).sum()} frames")
    print(f"  train-noGT : {(groups == _GROUP_TRAIN_NOGT).sum()} frames")
    print(f"  val        : {(groups == _GROUP_VAL).sum()} frames")
    print(f"  phases found: {sorted(unique_phases.tolist())}  (expected 0–{n_phases-1})")

    # ── sample ────────────────────────────────────────────────────────────────
    embeddings, phase_labels, groups, video_names, frame_orders = sample_embeddings(
        embeddings, phase_labels, groups, video_names, frame_orders, cfg
    )
    print(f"After sampling: {len(embeddings)} frames")

    # ── joint preprocessing ───────────────────────────────────────────────────
    print(f"Preprocessing {len(embeddings)} frames (dim={embeddings.shape[1]}) …")
    emb_proc = preprocess_embeddings(embeddings, cfg)

    # ── t-SNE ────────────────────────────────────────────────────────────────
    print("Running t-SNE …")
    coords, perplexity_used = run_tsne(emb_proc, cfg)
    print(f"t-SNE done. Perplexity used: {perplexity_used}")

    # ── plot ──────────────────────────────────────────────────────────────────
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

    path_combined = plot_tsne_phase(
        coords, phase_labels, groups, cfg, output_dir, timestamp
    )
    print(f"Saved combined plot : {path_combined}")

    # ── val GT label alignment (for 4th panel) ─────────────────────────────
    val_gt_aligned = None
    # [v2] val_labeled_h5_path is resolved by ConfigV2._resolve_visualize_tsne_phase()
    # from val_labeled_embedding_ref in configs_v2/visualize/tsne_phase.yaml
    val_labeled_h5 = cfg.get("val_labeled_h5_path")  # None when val_labeled_embedding_ref is ~
    if val_labeled_h5 and os.path.exists(val_labeled_h5):
        gt_phases = load_val_gt_phases(val_labeled_h5, cfg)
        if gt_phases:
            val_gt_aligned = np.full(len(phase_labels), -1, dtype=np.int64)
            val_mask = groups == _GROUP_VAL
            val_idx  = np.where(val_mask)[0]
            val_base = np.array([
                vn[4:] if vn.startswith("val_") else vn
                for vn in video_names[val_mask]
            ])
            val_ford = frame_orders[val_mask]
            for k, (vid, t) in enumerate(zip(val_base, val_ford)):
                if vid in gt_phases and t < len(gt_phases[vid]):
                    val_gt_aligned[val_idx[k]] = gt_phases[vid][t]
            n_matched = int((val_gt_aligned >= 0).sum())
            n_agree   = int(
                (phase_labels[val_mask][val_gt_aligned[val_mask] >= 0]
                 == val_gt_aligned[val_mask][val_gt_aligned[val_mask] >= 0]).sum()
            )
            print(
                f"Val GT matched: {n_matched} frames  |  "
                f"SVM phase accuracy: {n_agree}/{n_matched} "
                f"= {n_agree / max(n_matched, 1):.3f}"
            )
        else:
            print("[skip] No labeled videos in val labeled H5; 4th panel omitted.")
    else:
        if not val_labeled_h5:
            print("[skip] val_labeled_dataset_stem not set; 4th panel omitted.")
        else:
            print(f"[skip] val_labeled_h5 not found: {val_labeled_h5}")

    if not args.no_panels:
        path_panels = plot_tsne_phase_separate(
            coords, phase_labels, groups, cfg, output_dir, timestamp,
            val_gt_labels=val_gt_aligned,
        )
        if path_panels:
            print(f"Saved panel plot    : {path_panels}")

if __name__ == "__main__":
    main()
